# Generated by Django 4.0.2 on 2022-02-28 07:10

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=api.models.upload_file_to)),
                ('accounttype', models.CharField(choices=[('Employee', 'employee'), ('Employer', 'employer')], default='Employee', max_length=150)),
                ('profisional', models.CharField(max_length=150)),
                ('bio', models.TimeField(max_length=250)),
                ('address', models.CharField(max_length=150)),
                ('phone', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
