# Generated by Django 4.0.2 on 2022-02-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='accounttype',
            field=models.CharField(choices=[('Employee', 'employee'), ('Employer', 'employer')], max_length=150),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='bio',
            field=models.TextField(max_length=250),
        ),
    ]
