# Generated by Django 4.0.2 on 2022-03-19 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_profile_address_alter_user_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='image',
        ),
    ]
