# Generated by Django 4.0.2 on 2022-03-21 11:07

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='accounttype',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='profisional',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='image',
            field=models.ImageField(default='avarar.png', upload_to=api.models.upload_file_to),
        ),
    ]
