# Generated by Django 4.0.2 on 2022-03-27 19:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_profile',
            new_name='Userprofile',
        ),
    ]
