# Generated by Django 4.0.2 on 2022-03-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_address_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profisional',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
