# Generated by Django 4.0 on 2022-04-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='discription',
            field=models.CharField(max_length=350),
        ),
    ]
