# Generated by Django 4.0.4 on 2022-04-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessageToAoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('massage', models.CharField(max_length=500)),
            ],
        ),
    ]
