# Generated by Django 4.0.4 on 2022-04-27 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sendmessagetoaoo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SendMessageToAoo',
            new_name='SendMessageToApp',
        ),
    ]
