# Generated by Django 4.0.4 on 2022-04-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_sendmessagetoaoo_sendmessagetoapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessagetoapp',
            name='massage',
            field=models.CharField(max_length=1500),
        ),
    ]
