# Generated by Django 4.0 on 2022-07-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
